version: "3.8"

services:
  mysql:
    image: mysql:8.2.0
    container_name: mysql
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql-data:
